import std/[strutils, tables, sequtils, os, strformat]
import ../core/types
import ../parser/parser
import ../parser/lexer
import ../compiler/context
import ../compiler/analyzer
import ../compiler/symbols
import ./slots
import ./methods
import ./control
import ./expression
import ./blocks

# ============================================================================
# Module Generation
# Generates complete Nim modules from Harding source
# ============================================================================

proc mangleModuleName*(name: string): string =
  ## Convert module name to valid Nim identifier
  ## Module names starting with digits are invalid in Nim, use -o flag to specify output name
  return name

proc genModuleHeader*(ctx: var CompilerContext, moduleName: string, mixed: bool = false): string =
  ## Generate module header with imports and documentation
  ## mixed: if true, include interpreter imports for hybrid execution
  var output = ""

  output.add("## Generated by Harding Compiler\n")
  output.add("## Module: " & moduleName & "\n")
  if mixed:
    output.add("## Mode: Mixed (compiled + interpreter fallback)\n")
  else:
    output.add("## Mode: Pure compilation\n")
  output.add("## Do not edit - generated from .hrd source\n\n")

  output.add("# Imports\n")
  output.add("import std/[tables, sequtils]\n")
  output.add("import ../src/harding/core/[types]\n")
  output.add("import ../src/harding/interpreter/[objects, activation]\n\n")

  output.add("# Runtime imports\n")
  output.add("import ../src/harding/runtime/[runtime]\n")
  if mixed:
    output.add("# Mixed mode: interpreter embedded for fallback\n")
    output.add("import ../src/harding/interpreter/[vm]\n")
    output.add("import ../src/harding/core/[scheduler]\n\n")
  else:
    output.add("\n")

  return output

proc genClassConstants*(cls: ClassInfo): string =
  ## Generate Nim type definition for a class
  let clsName = mangleClass(cls.name)
  var parentName = "HardingObject"
  if cls.parent != nil:
    parentName = mangleClass(cls.parent.name) & "Obj"
  let slots = cls.getAllSlots()
  
  var output = fmt("# {cls.name} Class\n")
  output.add("###################\n\n")
  
  # Generate Nim object type with slots as fields
  # TODO: Eventually when we generate native methods directly, we can remove
  # classRef and toValue() - methods will be called directly instead of via sendMessage
  output.add("type\n")
  output.add(fmt("  {clsName}Obj* {{.inheritable.}} = object of {parentName}\n"))
  output.add(fmt("    classRef*: Class  ## Store class reference for toValue() (temporary - see above)\n"))
  
  # Slot fields - use NodeValue for flexibility in Harding
  for slot in slots:
    if not slot.isInherited:
      let slotName = mangleSlot(slot.name)
      output.add(fmt("    {slotName}*: NodeValue\n"))
  
  output.add(fmt("  {clsName}* = ref {clsName}Obj\n\n"))
  
  # Constructor
  output.add(fmt("proc new{clsName}*(): {clsName} =\n"))
  output.add(fmt("  ## Create new {cls.name} instance\n"))
  output.add(fmt("  result = {clsName}(new({clsName}Obj))\n"))
  # TODO: User-defined classes aren't automatically in globals. This is a fundamental
  # limitation - we'd need interpreter changes to register classes. For now, use Object.
  output.add(fmt("  if hybridInterpreter != nil:\n"))
  output.add(fmt("    if \"{cls.name}\" in hybridInterpreter.globals[]:\n"))
  output.add(fmt("      let clsVal = hybridInterpreter.globals[][\"{cls.name}\"]\n"))
  output.add(fmt("      if clsVal.kind == vkInstance and clsVal.instVal != nil:\n"))
  output.add(fmt("        result.classRef = clsVal.instVal.class\n"))
  output.add(fmt("    elif \"Object\" in hybridInterpreter.globals[]:\n"))
  output.add(fmt("      let objVal = hybridInterpreter.globals[][\"Object\"]\n"))
  output.add(fmt("      if objVal.kind == vkInstance and objVal.instVal != nil:\n"))
  output.add(fmt("        result.classRef = objVal.instVal.class\n"))
  for slot in slots:
    if not slot.isInherited:
      output.add(fmt("  result.{mangleSlot(slot.name)} = NodeValue(kind: vkNil)\n"))
  output.add("\n")

  # toValue - convert native type to NodeValue using stored classRef
  # TODO: Remove when native method generation is complete
  output.add(fmt("proc toValue*(self: {clsName}): NodeValue =\n"))
  output.add(fmt("  ## Convert {cls.name} to NodeValue for sendMessage interop\n"))
  output.add(fmt("  let inst = Instance(kind: ikObject, class: self.classRef, isNimProxy: true, nimValue: cast[pointer](self))\n"))
  output.add(fmt("  return NodeValue(kind: vkInstance, instVal: inst)\n"))
  output.add("\n")

  return output

proc genClassInit*(cls: ClassInfo): string =
  ## Generate class initialization procedure (legacy - kept for compatibility)
  let clsName = mangleClass(cls.name)
  
  return fmt("""
# Legacy class init - use new{clsName}() constructor instead
# proc init_{clsName}*(): {clsName} = new{clsName}()

""")

proc isClassDefinition(node: Node): bool =
  ## Check if a node is a class definition (derive: or deriveWithAccessors: chain)
  # Check for Class := Parent derive: ... pattern (nkAssign from :=)
  if node.kind == nkAssign:
    let assign = node.AssignNode
    if assign.expression != nil and assign.expression.kind == nkMessage:
      let valMsg = assign.expression.MessageNode
      if valMsg.selector in ["derive:", "derive", "deriveWithAccessors:", "deriveWithAccessors"]:
        return true
    return false
  # Check for at:put: message pattern
  elif node.kind == nkMessage:
    let msg = node.MessageNode
    if msg.selector == "at:put:":
      if msg.arguments.len >= 2 and msg.arguments[1].kind == nkMessage:
        let valMsg = msg.arguments[1].MessageNode
        if valMsg.selector in ["derive:", "derive", "deriveWithAccessors:", "deriveWithAccessors"]:
          return true
  return false

proc isMethodDefinition(node: Node): bool =
  ## Check if a node is a method definition (selector:put: or classSelector:put:)
  if node.kind != nkMessage:
    return false
  let msg = node.MessageNode
  return msg.selector in ["selector:put:", "classSelector:put:"]

proc extractClassAndMethodDefs(nodes: seq[Node]): tuple[defs: seq[Node], topLevel: seq[Node]] =
  ## Separate class/method definitions from top-level executable statements
  var defs: seq[Node] = @[]
  var topLevel: seq[Node] = @[]

  for node in nodes:
    if node.isClassDefinition or node.isMethodDefinition:
      defs.add(node)
    else:
      topLevel.add(node)

  return (defs, topLevel)

proc genMainProc*(ctx: var CompilerContext, topLevel: seq[Node], moduleName: string,
                  blockReg: BlockRegistry = nil, mixed: bool = false,
                  analysis: AnalysisResult = nil): string =
  ## Generate the main() procedure for top-level statement execution
  var output = ""

  output.add("# Main Entry Point\n")
  output.add("##################\n\n")

  output.add("proc main(): int =\n")
  output.add("  ## Main entry point for ")
  output.add(moduleName)
  output.add("\n")

  # Initialize runtime
  output.add("  initRuntime()\n")
  output.add("  initHybridRuntime()\n")
  output.add("\n")

  # Create generation context for top-level code, sharing block registry if provided
  var classReg: TableRef[string, ClassInfo] = nil
  if analysis != nil:
    classReg = newTable[string, ClassInfo]()
    for name, cls in analysis.classes:
      classReg[name] = cls
  var genCtx = newGenContext(nil, mixed, classReg)
  if blockReg != nil:
    genCtx.blockRegistry = blockReg

  # Check if any blocks have non-local returns - if so, wrap in try/except
  var hasNonLocalReturn = false
  if blockReg != nil:
    for blockInfo in blockReg.getAllBlocks():
      if blockInfo.hasNonLocalReturn:
        hasNonLocalReturn = true
        break

  if hasNonLocalReturn:
    output.add("  try:\n")

  # Generate code for each top-level statement
  for node in topLevel:
    let stmtCode = genTopLevelStatement(genCtx, node)
    if stmtCode.len > 0:
      # Indent the statement (extra level if wrapped in try)
      for line in stmtCode.splitLines():
        if hasNonLocalReturn:
          output.add("    ")
        else:
          output.add("  ")
        output.add(line)
        output.add("\n")

  if hasNonLocalReturn:
    # Return exit code 0 in normal case
    output.add("    return 0\n")
    output.add("  except NonLocalReturnException as nlr:\n")
    output.add("    ## Non-local return from block - print and return the value\n")
    output.add("    echo nlr.value.toString()\n")
    output.add("    return 0\n")
  else:
    # Return exit code 0
    output.add("\n  return 0\n")

  return output

proc genModule*(ctx: var CompilerContext, nodes: seq[Node],
                moduleName: string, mixed: bool = false): string =
  ## Generate complete Nim module from parsed nodes
  ## mixed: if true, embed interpreter for fallback on unsupported features
  var output = ""

  output.add(genModuleHeader(ctx, moduleName, mixed))
  output.add(genRuntimeHelperMethods())
  output.add("\n")
  output.add(genBlockRuntimeHelpers())
  output.add("\n")

  # Separate class/method definitions from top-level statements
  let (classDefs, topLevel) = extractClassAndMethodDefs(nodes)

  # Analyze classes
  let analysis = buildClassGraph(nodes)

  # Resolve slot indices
  ctx.resolveSlotIndices()

  # Generate base HardingObject type first
  output.add("# Base Object Type\n")
  output.add("##################\n\n")
  output.add("type\n")
  output.add("  HardingObject* {.inheritable.} = object\n")
  output.add("    className*: string\n")
  output.add("  HardingObjectRef* = ref HardingObject\n\n")

  # Generate for each class
  for cls in analysis.classes.values:
    output.add(genClassConstants(cls))
    output.add(genSlotAccessors(cls))
    output.add(genClassInit(cls))

  # Generate control flow methods
  output.add("\n")
  output.add("# Control Flow Methods\n")
  output.add("######################\n\n")

  output.add(genWhileTrueMethod())
  output.add(genWhileFalseMethod())
  output.add(genIfTrueIfFalseMethod())
  output.add(genTimesRepeatMethod())

  # Generate binary operators
  output.add("\n")
  output.add("# Binary Operators\n")
  output.add("#################\n\n")

  for op in ["+", "-", "*", "/"]:
    output.add(genBinaryOpMethod(op))

  # Generate comparison operators
  output.add("\n")
  output.add("# Comparison Operators\n")
  output.add("#####################\n\n")

  for op in ["<", "<=", ">", ">=", "=", "==", "~="]:
    output.add(genComparisonMethod(op))

  # Generate integer division and modulo operators
  output.add("\n")
  output.add("# Integer Division and Modulo\n")
  output.add("#############################\n\n")

  output.add(genBinaryOpMethod("//"))
  output.add(genBinaryOpMethod("\\"))
  output.add(genBinaryOpMethod("%"))

  # Generate block procedure definitions (AFTER runtime helpers so they can use nt_* functions)
  output.add("\n")
  output.add("# Block Procedures\n")
  output.add("##################\n\n")

  # Create a block registry and collect blocks
  # Note: top-level variables are NOT passed as knownGlobals because they are
  # locals of main() and need to be captured by block procs at module level.
  # Only true globals (class names) would be excluded from captures.
  var blockReg = newBlockRegistry()
  for node in topLevel:
    collectBlocks(blockReg, node)

  # Generate environment structs for blocks with captures
  for blockInfo in blockReg.getAllBlocks():
    let structDef = generateEnvStructDef(blockInfo)
    if structDef.len > 0:
      output.add(structDef)
      output.add("\n\n")

  # Generate forward declarations for all block procedures first
  # This allows blocks to reference each other regardless of definition order
  for blockInfo in blockReg.getAllBlocks():
    output.add(generateBlockProcSignature(blockInfo))
    output.add("\n")
  output.add("\n")

  # Generate block procedure bodies using real code generation
  var blockGenCtx = newGenContext(nil, mixed)
  blockGenCtx.blockRegistry = blockReg  # Share the registry with collected blocks
  for blockInfo in blockReg.getAllBlocks():
    output.add(generateBlockProcSignature(blockInfo))
    output.add(" =\n")
    let body = genBlockBody(blockGenCtx, blockInfo.blockNode, blockInfo.captures,
                            blockInfo.hasNonLocalReturn, blockInfo.envStructName)
    if body.len > 0:
      output.add(body)
    else:
      output.add("  return NodeValue(kind: vkNil)\n")
    output.add("\n\n")

  # Generate main proc for top-level statements, sharing block registry
  output.add(genMainProc(ctx, topLevel, moduleName, blockReg, mixed, analysis))

  # Module initialization
  output.add("\n")
  output.add("# Module Initialization\n")
  output.add("######################\n")

  output.add(fmt("""
proc init_{moduleName}*() =
  ## Initialize {moduleName} module
  initRuntime()
  initHybridRuntime()
  echo "Module loaded: {moduleName}"

when isMainModule:
  discard main()
"""))

  return output

proc compileFile*(inputPath: string, outputDir = "./build"): string =
  ## Compile a Harding source file to Nim
  let source = readFile(inputPath)
  let tokens = lex(source)
  var parser = initParser(tokens)
  let nodes = parser.parseStatements()

  if parser.hasError:
    echo "Parse error: " & parser.errorMsg
    return ""

  let moduleName = inputPath.extractFilename().changeFileExt("")

  var ctx = newCompiler(outputDir, moduleName)
  let nimCode = genModule(ctx, nodes, moduleName)

  let outputPath = outputDir / moduleName & ".nim"
  createDir(outputDir)
  writeFile(outputPath, nimCode)

  return outputPath
