import std/[strutils, tables, os, strformat]
import ../core/types
import ../parser/parser
import ../parser/lexer
import ../compiler/context
import ../compiler/analyzer
import ../compiler/symbols
import ./methods
import ./control
import ./expression
import ./blocks

# ============================================================================
# Module Generation
# Generates complete Nim modules from Harding source
# ============================================================================

proc mangleModuleName*(name: string): string =
  ## Convert module name to valid Nim identifier
  ## Module names starting with digits are invalid in Nim, use -o flag to specify output name
  return name

proc genModuleHeader*(ctx: var CompilerContext, moduleName: string,
                      includeOsImport: bool = false): string =
  ## Generate module header with imports and documentation
  var output = ""

  output.add("## Generated by Harding Compiler\n")
  output.add("## Module: " & moduleName & "\n")
  output.add("## Do not edit - generated from .hrd source\n\n")

  output.add("# Imports\n")
  if includeOsImport:
    output.add("import std/[tables, sequtils, os]\n")
  else:
    output.add("import std/[tables, sequtils]\n")
  output.add("import ../src/harding/core/[types]\n")
  output.add("import ../src/harding/interpreter/[objects, activation]\n\n")

  output.add("# Runtime imports\n")
  output.add("import ../src/harding/runtime/[runtime]\n\n")

  return output

proc genClassConstants*(cls: ClassInfo): string =
  ## Generate native Nim type for Harding class with slot accessors
  let clsName = mangleClass(cls.name)
  let slots = cls.getAllSlots()
  
  # Keep generated native objects rooted at HardingObject.
  # Language-level inheritance is handled by runtime method dispatch tables.
  let parentName = "HardingObject"
  
  var output = fmt("# {cls.name} Class\n")
  output.add("###################\n\n")
  
  # Generate Nim object type with slots as fields
  # TODO: Eventually when we generate native methods directly, we can remove
  # classRef and toValue() - methods will be called directly instead of via sendMessage
  output.add("type\n")
  output.add(fmt("  {clsName}Obj* {{.inheritable.}} = object of {parentName}\n"))
  output.add(fmt("    classRef*: Class  ## Store class reference for toValue() (temporary - see above)\n"))
  
  # Slot fields - include inherited slots so each native class is self-contained
  for slot in slots:
    let slotName = mangleSlot(slot.name)
    output.add(fmt("    {slotName}*: NodeValue\n"))
  
  output.add(fmt("  {clsName}* = ref {clsName}Obj\n\n"))
  
  # Constructor
  output.add(fmt("proc new{clsName}*(): {clsName} =\n"))
  output.add(fmt("  ## Create new {cls.name} instance\n"))
  output.add(fmt("  result = {clsName}(new({clsName}Obj))\n"))
  output.add(fmt("  result.className = \"{cls.name}\"\n"))
  output.add(fmt("  registerNimProxyClassName(cast[pointer](result), \"{cls.name}\")\n"))
  # Get class reference from interpreter globals (temporary workaround)
  # This registers the class so toValue() can create proper Instance wrapper
  output.add(fmt("  if hybridInterpreter != nil:\n"))
  output.add(fmt("    if \"{cls.name}\" in hybridInterpreter.globals[]:\n"))
  output.add(fmt("      let clsVal = hybridInterpreter.globals[][\"{cls.name}\"]\n"))
  output.add(fmt("      if clsVal.kind == vkClass:\n"))
  output.add(fmt("        result.classRef = clsVal.classVal\n"))
  output.add(fmt("      elif clsVal.kind == vkInstance and clsVal.instVal != nil:\n"))
  output.add(fmt("        result.classRef = clsVal.instVal.class\n"))
  output.add(fmt("    elif \"Object\" in hybridInterpreter.globals[]:\n"))
  output.add(fmt("      let objVal = hybridInterpreter.globals[][\"Object\"]\n"))
  output.add(fmt("      if objVal.kind == vkInstance and objVal.instVal != nil:\n"))
  output.add(fmt("        result.classRef = objVal.instVal.class\n"))
  for slot in slots:
    output.add(fmt("  result.{mangleSlot(slot.name)} = NodeValue(kind: vkNil)\n"))
  output.add("\n")

  # toValue - convert native type to NodeValue using stored classRef
  # TODO: Remove when native method generation is complete
  output.add(fmt("proc toValue*(self: {clsName}): NodeValue =\n"))
  output.add(fmt("  ## Convert {cls.name} to NodeValue for sendMessage interop\n"))
  output.add(fmt("  let inst = Instance(kind: ikObject, class: self.classRef, isNimProxy: true, nimValue: cast[pointer](self))\n"))
  output.add(fmt("  return NodeValue(kind: vkInstance, instVal: inst)\n"))
  output.add("\n")
  
  return output

proc genClassInit*(cls: ClassInfo): string =
  ## Generate class initialization procedure (legacy - kept for compatibility)
  let clsName = mangleClass(cls.name)
  
  return fmt("""
# Legacy class init - use new{clsName}() constructor instead
# proc init_{clsName}*(): {clsName} = new{clsName}()

""")

proc genSlotAccessors*(cls: ClassInfo): string =
  ## Generate native Nim slot accessor procs for a class
  let clsName = mangleClass(cls.name)
  let slots = cls.getAllSlots()
  
  var output = ""
  if slots.len == 0:
    return output
  
  output.add("# Slot accessors\n")
  output.add("################################\n\n")
  
  for slot in slots:
    if slot.isInherited:
      continue
    let slotName = mangleSlot(slot.name)
    
    # Getter
    output.add(fmt("proc get{slotName}*(self: {clsName}): NodeValue =\n"))
    output.add(fmt("  ## Get slot '{slot.name}' from {cls.name}\n"))
    output.add(fmt("  return self[].{slotName}\n\n"))
    
    # Setter  
    output.add(fmt("proc set{slotName}*(self: {clsName}, value: NodeValue): NodeValue =\n"))
    output.add(fmt("  ## Set slot '{slot.name}' on {cls.name}\n"))
    output.add(fmt("  self[].{slotName} = value\n"))
    output.add(fmt("  return value\n\n"))
  
  return output

proc isClassDefinition(node: Node): bool =
  ## Check if a node is a class definition (derive: chain)
  let (className, _, _) = extractDeriveChain(node)
  return className.len > 0

proc isMethodDefinition(node: Node): bool =
  ## Check if a node is a method definition (selector:put: or classSelector:put:)
  if node.kind != nkMessage:
    return false
  let msg = node.MessageNode
  return msg.selector in ["selector:put:", "classSelector:put:"]

proc extractClassAndMethodDefs(nodes: seq[Node]): tuple[defs: seq[Node], topLevel: seq[Node]] =
  ## Separate class/method definitions from top-level executable statements
  var defs: seq[Node] = @[]
  var topLevel: seq[Node] = @[]

  for node in nodes:
    if node.isClassDefinition or node.isMethodDefinition:
      defs.add(node)
    else:
      topLevel.add(node)

  return (defs, topLevel)

proc extractMethodDefs(nodes: seq[Node]): seq[tuple[className, selector: string, params: seq[string], body: seq[Node]]] =
  ## Extract method definitions from AST nodes
  ## Returns (className, selector, params, body) for each method
  result = @[]
  
  for node in nodes:
    if node.kind == nkMessage:
      let msg = node.MessageNode
      if msg.selector == "selector:put:" and msg.arguments.len >= 2:
        var bodyBlock: BlockNode = nil
        if msg.arguments[1].kind == nkBlock:
          bodyBlock = msg.arguments[1].BlockNode
        elif msg.arguments[1].kind == nkLiteral:
          let litVal = msg.arguments[1].LiteralNode.value
          if litVal.kind == vkBlock:
            bodyBlock = litVal.blockVal
        
        if msg.arguments[0].kind == nkLiteral and bodyBlock != nil:
          let litVal = msg.arguments[0].LiteralNode.value
          let selectorName = if litVal.kind == vkSymbol: litVal.symVal 
                             elif litVal.kind == vkString: litVal.strVal
                             else: ""
          
          var className = ""
          if msg.receiver != nil and msg.receiver.kind == nkIdent:
            className = msg.receiver.IdentNode.name
          
          if className.len > 0 and selectorName.len > 0:
            result.add((className, selectorName, bodyBlock.parameters, bodyBlock.body))

proc genCompiledMethods*(methodDefs: seq[tuple[className, selector: string, params: seq[string], body: seq[Node]]],
                         compiledClasses: seq[string], classInfo: Table[string, ClassInfo]): string =
  ## Generate compiled method procs from extracted method definitions
  var output = ""
  var registrationCode = ""
  
  if methodDefs.len == 0:
    # Still generate registration stub
    output.add("# Method Registration\n")
    output.add("#####################\n\n")
    output.add("proc registerCompiledMethods*() =\n")
    output.add("  discard 0\n")
    output.add("\n")
    return output
  
  output.add("\n# Compiled Methods\n")
  output.add("##################\n\n")
  
  for md in methodDefs:
    let clsName = md.className
    let selector = md.selector
    let params = md.params
    let body = md.body
    
    # Skip if class not in compiled classes
    if clsName notin compiledClasses:
      continue
    
    let mangledClass = mangleClass(clsName)
    let mangledSelector = mangleSelector(selector)
    let procName = fmt("{mangledClass}_{mangledSelector}")
    
    output.add(fmt("proc {procName}*(self: NodeValue, args: seq[NodeValue]): NodeValue =\n"))

    for i, paramName in params:
      output.add(fmt("  let {paramName} = if args.len > {i}: args[{i}] else: NodeValue(kind: vkNil)\n"))
    
    if body.len > 0:
      var genCtx = newGenContext(nil, compiledClasses, classInfo)
      genCtx.inMethod = true
      
      if clsName in classInfo:
        genCtx.cls = classInfo[clsName]
      
      genCtx.globals.add("self")
      genCtx.setVariableType("self", clsName, true)
      for paramName in params:
        genCtx.parameters.add(paramName)
      
      let bodyLen = body.len
      for i, stmt in body:
        let isLast = (i == bodyLen - 1) and selector != "initialize"
        let stmtCode = genMethodBodyStatement(genCtx, stmt, isLast)
        if stmtCode.len > 0:
          for line in stmtCode.splitLines():
            output.add("  ")
            output.add(line)
            output.add("\n")

      # Smalltalk convention: initialize methods return self unless explicit ^ used
      if selector == "initialize":
        output.add("  return self\n")
    
    output.add("\n\n")
    
    # Add registration call
    registrationCode.add(fmt("  registerCompiledMethod(\"{clsName}\", \"{selector}\", {procName})\n"))
  
  # Add registration procs (stubs if no methods/superclasses)
  output.add("# Method Registration\n")
  output.add("#####################\n\n")
  output.add("proc registerCompiledMethods*() =\n")
  if registrationCode.len > 0:
    output.add(registrationCode)
  else:
    output.add("  discard 0\n")
  output.add("\n")
  
  return output

proc isHardingCompileBlock(node: Node): bool =
  ## Check if node is "Harding compile: [block]"
  if node.kind != nkMessage:
    return false
  let msg = node.MessageNode
  if msg.selector != "compile:":
    return false
  if msg.receiver == nil or msg.receiver.kind != nkIdent:
    return false
  return msg.receiver.IdentNode.name == "Harding"

proc isHardingMainBlock(node: Node): bool =
  ## Check if node is "Harding main: [block]"
  if node.kind != nkMessage:
    return false
  let msg = node.MessageNode
  if msg.selector != "main:":
    return false
  if msg.receiver == nil or msg.receiver.kind != nkIdent:
    return false
  return msg.receiver.IdentNode.name == "Harding"

proc extractHardingBlocks(nodes: seq[Node]): tuple[compileBlock, mainBlock: BlockNode, other: seq[Node]] =
  ## Extract Harding compile: and main: blocks from nodes
  result = (nil, nil, @[])
  
  for node in nodes:
    if node.isHardingCompileBlock:
      if node.MessageNode.arguments.len > 0 and node.MessageNode.arguments[0].kind == nkBlock:
        result.compileBlock = node.MessageNode.arguments[0].BlockNode
    elif node.isHardingMainBlock:
      if node.MessageNode.arguments.len > 0 and node.MessageNode.arguments[0].kind == nkBlock:
        result.mainBlock = node.MessageNode.arguments[0].BlockNode
    else:
      result.other.add(node)

proc genMainProc*(ctx: var CompilerContext, topLevel: seq[Node], moduleName: string,
                  blockReg: BlockRegistry = nil, compiledClasses: seq[string] = @[],
                  classInfo: Table[string, ClassInfo] = initTable[string, ClassInfo](),
                  mixed: bool = false, sourceFile: string = "",
                  injectMainArgsVar: bool = false): string =
  ## Generate the main() procedure for top-level statement execution
  var output = ""

  output.add("# Main Entry Point\n")
  output.add("##################\n\n")

  output.add("proc main(): int =\n")
  output.add("  ## Main entry point for ")
  output.add(moduleName)
  output.add("\n")

  # Initialize runtime
  output.add("  initRuntime()\n")
  output.add("  registerCompiledMethods()\n")
  output.add("  registerSuperclassHierarchy()\n\n")

  # If mixed mode, initialize hybrid runtime with source file
  if mixed and sourceFile.len > 0:
    output.add(fmt("  initHybridRuntime(@[\"{sourceFile}\"])\n\n"))

  if injectMainArgsVar:
    output.add("  var hardingArgsElems: seq[NodeValue] = @[]\n")
    output.add("  for arg in commandLineParams():\n")
    output.add("    hardingArgsElems.add(NodeValue(kind: vkString, strVal: arg))\n")
    output.add("  var args {.used.} = NodeValue(kind: vkArray, arrayVal: hardingArgsElems)\n\n")

  # Create generation context for top-level code, sharing block registry if provided
  var genCtx = newGenContext(nil, compiledClasses, classInfo, mixed)
  if injectMainArgsVar:
    genCtx.locals.add("args")
    genCtx.globals.add("args")
  if blockReg != nil:
    genCtx.blockRegistry = blockReg

  # Generate code for each top-level statement
  for node in topLevel:
    let stmtCode = genTopLevelStatement(genCtx, node)
    if stmtCode.len > 0:
      # Indent the statement
      for line in stmtCode.splitLines():
        output.add("  ")
        output.add(line)
        output.add("\n")

  # Return exit code 0
  output.add("\n  return 0\n")

  return output

proc genModule*(ctx: var CompilerContext, nodes: seq[Node],
                moduleName: string, mixed: bool = false, sourceFile: string = "",
                reflectedClasses: Table[string, ClassInfo] = initTable[string, ClassInfo](),
                injectMainArgsVar: bool = false): string =
  ## Generate complete Nim module from parsed nodes
  ## mixed: if true, embed interpreter for fallback on unsupported features
  ## sourceFile: path to source .hrd file for class registration in interpreter
  ## reflectedClasses: optional class info from interpreter execution (for dynamic classes)
  var output = ""

  output.add(genModuleHeader(ctx, moduleName, includeOsImport = injectMainArgsVar))
  output.add(genRuntimeHelperMethods())
  output.add("\n")
  output.add(genBlockRuntimeHelpers())
  output.add("\n")

  # Extract Harding compile: and main: blocks first
  let hardingBlocks = nodes.extractHardingBlocks()
  
  # Determine what to compile as main:
  # If there's a Harding main: block, use its body; otherwise use top-level code.
  var mainBodyNodes: seq[Node]
  if hardingBlocks.mainBlock != nil:
    mainBodyNodes = hardingBlocks.mainBlock.body
  else:
    # Use everything that's not a compile block
    mainBodyNodes = hardingBlocks.other

  # Build the definition source used for class/method extraction.
  # compile: contributes definitions for codegen but does NOT run at runtime in generated main().
  var defsSourceNodes = mainBodyNodes
  if hardingBlocks.compileBlock != nil:
    defsSourceNodes = hardingBlocks.compileBlock.body & defsSourceNodes

  let (classDefs, _) = extractClassAndMethodDefs(defsSourceNodes)
  let (_, executableMainNodes) = extractClassAndMethodDefs(mainBodyNodes)

  # Analyze classes from AST and optionally enrich slots from reflected runtime classes.
  # This avoids pulling unrelated stdlib/internal classes into generated output.
  let analysis = block:
    let astAnalysis = buildClassGraph(defsSourceNodes)
    if reflectedClasses.len == 0:
      astAnalysis
    else:
      let merged = newAnalysisResult()
      merged.classes = initTable[string, ClassInfo]()

      # First pass: create class entries and slot sets
      for className, astCls in astAnalysis.classes.pairs:
        let mergedCls = newClassInfo(className)
        let slotSource = if className in reflectedClasses: reflectedClasses[className] else: astCls
        for slot in slotSource.slots:
          discard mergedCls.addSlot(slot.name, slot.constraint)
        merged.classes[className] = mergedCls

      # Second pass: wire parent links using AST class graph names
      for className, astCls in astAnalysis.classes.pairs:
        if astCls.parent != nil and astCls.parent.name in merged.classes:
          merged.classes[className].parent = merged.classes[astCls.parent.name]

      merged

  # Resolve slot indices
  ctx.resolveSlotIndices()
  
  # Collect compiled class names for native instantiation
  var compiledClassNames: seq[string] = @[]
  for cls in analysis.classes.values:
    compiledClassNames.add(cls.name)

  # Generate base HardingObject type first
  output.add("# Base Object Type\n")
  output.add("##################\n\n")
  output.add("type\n")
  output.add("  HardingObject* {.inheritable.} = object\n")
  output.add("    className*: string\n")
  output.add("  HardingObjectRef* = ref HardingObject\n\n")

  # Extract method definitions from class and compile blocks
  let methodDefs = extractMethodDefs(classDefs)

  # Generate for each class
  for cls in analysis.classes.values:
    output.add(genClassConstants(cls))
    output.add(genSlotAccessors(cls))
    output.add(genClassInit(cls))

  # Generate superclass hierarchy registration
  var superclassCalls = ""

  # Static inheritance from class analysis (derive:, deriveWithAccessors:)
  for cls in analysis.classes.values:
    if cls.parent != nil and cls.parent.name.len > 0:
      superclassCalls.add(fmt("  registerSuperclass(\"{cls.name}\", \"{cls.parent.name}\")\n"))

  # Static inheritance from derive receiver (includes parents outside compiled set, e.g. Object)
  for node in classDefs:
    let (className, parentName, _) = extractDeriveChain(node)
    if className.len > 0 and parentName.len > 0 and className != parentName:
      superclassCalls.add(fmt("  registerSuperclass(\"{className}\", \"{parentName}\")\n"))

  # Dynamic inheritance from explicit addSuperclass: calls
  for node in mainBodyNodes:
    if node.kind == nkMessage:
      let msg = node.MessageNode
      if msg.selector == "addSuperclass:" and msg.arguments.len >= 1:
        if msg.receiver != nil and msg.receiver.kind == nkIdent:
          let subclassName = msg.receiver.IdentNode.name
          if msg.arguments[0].kind == nkIdent:
            let superclassName = msg.arguments[0].IdentNode.name
            superclassCalls.add(fmt("  registerSuperclass(\"{subclassName}\", \"{superclassName}\")\n"))
  
  if superclassCalls.len > 0:
    output.add("\n")
    output.add("# Superclass Hierarchy\n")
    output.add("######################\n\n")
    output.add("proc registerSuperclassHierarchy*() =\n")
    output.add(superclassCalls)
    output.add("\n")
  else:
    output.add("proc registerSuperclassHierarchy*() = discard 0\n\n")

  # Generate control flow methods (must come before block procedures that may use them)
  output.add("\n")
  output.add("# Control Flow Methods\n")
  output.add("######################\n\n")

  output.add(genWhileTrueMethod())
  output.add(genWhileFalseMethod())
  output.add(genIfTrueIfFalseMethod())
  output.add(genTimesRepeatMethod())

  # Generate binary operators (must come before block procedures that may use them)
  output.add("\n")
  output.add("# Binary Operators\n")
  output.add("#################\n\n")

  for op in ["+", "-", "*", "/"]:
    output.add(genBinaryOpMethod(op))

  # Generate comparison operators
  output.add("\n")
  output.add("# Comparison Operators\n")
  output.add("#####################\n\n")

  for op in ["<", "<=", ">", ">=", "=", "==", "~="]:
    output.add(genComparisonMethod(op))

  # Generate integer division and modulo operators
  output.add("\n")
  output.add("# Integer Division and Modulo\n")
  output.add("#############################\n\n")

  output.add(genBinaryOpMethod("//"))
  output.add(genBinaryOpMethod("\\"))
  output.add(genBinaryOpMethod("%"))

  # Generate compiled methods from user definitions after primitive operators,
  # so compiled method bodies can call nt_* helpers without forward declarations.
  output.add(genCompiledMethods(methodDefs, compiledClassNames, analysis.classes))

  # Create a block registry and collect blocks
  # Note: top-level variables are NOT passed as knownGlobals because they are
  # locals of main() and need to be captured by block procs at module level.
  # Only true globals (class names) would be excluded from captures.
  var blockReg = newBlockRegistry()
  for node in mainBodyNodes:
    collectBlocks(blockReg, node)

  # Generate block procedure definitions (after primitives so they can reference them)
  output.add("\n")
  output.add("# Block Procedures\n")
  output.add("##################\n\n")

  # Generate environment structs for blocks with captures
  for blockInfo in blockReg.getAllBlocks():
    let structDef = generateEnvStructDef(blockInfo)
    if structDef.len > 0:
      output.add(structDef)
      output.add("\n\n")

  # Generate forward declarations for block procedures first
  # This allows blocks to reference each other regardless of definition order
  for blockInfo in blockReg.getAllBlocks():
    output.add(generateBlockProcSignature(blockInfo))
    output.add("\n")
  output.add("\n")

  # Generate block procedure bodies using real code generation
  var blockGenCtx = newGenContext(nil, compiledClassNames, analysis.classes, mixed)
  blockGenCtx.blockRegistry = blockReg  # Share the registry so nested blocks can be found
  for blockInfo in blockReg.getAllBlocks():
    output.add(generateBlockProcSignature(blockInfo))
    output.add(" =\n")
    let body = genBlockBody(blockGenCtx, blockInfo.blockNode, blockInfo.captures,
                            blockInfo.hasNonLocalReturn, blockInfo.envStructName)
    if body.len > 0:
      output.add(body)
    else:
      output.add("  return NodeValue(kind: vkNil)\n")
    output.add("\n\n")

  # Generate main proc for top-level statements, sharing block registry
  output.add(genMainProc(ctx, executableMainNodes, moduleName, blockReg, compiledClassNames,
                         analysis.classes, mixed, sourceFile, injectMainArgsVar))

  # Module initialization
  output.add("\n")
  output.add("# Module Initialization\n")
  output.add("######################\n")

  output.add(fmt("""
proc init_{moduleName}*() =
  ## Initialize {moduleName} module
  initRuntime()
  registerCompiledMethods()
  echo "Module loaded: {moduleName}"

when isMainModule:
  discard main()
"""))

  return output

proc compileFile*(inputPath: string, outputDir = "./build"): string =
  ## Compile a Harding source file to Nim
  let source = readFile(inputPath)
  let tokens = lex(source)
  var parser = initParser(tokens)
  let nodes = parser.parseStatements()

  if parser.hasError:
    echo "Parse error: " & parser.errorMsg
    return ""

  let moduleName = inputPath.extractFilename().changeFileExt("")

  var ctx = newCompiler(outputDir, moduleName)
  let nimCode = genModule(ctx, nodes, moduleName)

  let outputPath = outputDir / moduleName & ".nim"
  createDir(outputDir)
  writeFile(outputPath, nimCode)

  return outputPath
