import std/[strutils, tables, os, strformat]
import ../core/types
import ../parser/parser
import ../parser/lexer
import ../compiler/context
import ../compiler/analyzer
import ../compiler/symbols
import ./methods
import ./control
import ./expression
import ./blocks

# ============================================================================
# Module Generation
# Generates complete Nim modules from Harding source
# ============================================================================

proc mangleModuleName*(name: string): string =
  ## Convert module name to valid Nim identifier
  ## Module names starting with digits are invalid in Nim, use -o flag to specify output name
  return name

proc genModuleHeader*(ctx: var CompilerContext, moduleName: string): string =
  ## Generate module header with imports and documentation
  var output = ""

  output.add("## Generated by Harding Compiler\n")
  output.add("## Module: " & moduleName & "\n")
  output.add("## Do not edit - generated from .hrd source\n\n")

  output.add("# Imports\n")
  output.add("import std/[tables, sequtils]\n")
  output.add("import ../src/harding/core/[types]\n")
  output.add("import ../src/harding/interpreter/[objects, activation]\n\n")

  output.add("# Runtime imports\n")
  output.add("import ../src/harding/runtime/[runtime]\n\n")

  return output

proc genClassConstants*(cls: ClassInfo): string =
  ## Generate native Nim type for Harding class with slot accessors
  let clsName = mangleClass(cls.name)
  let slots = cls.getAllSlots()
  
  # Determine parent class name
  var parentName = "HardingObject"
  if cls.parent != nil:
    parentName = "Class_" & cls.parent.name
  
  var output = fmt("# {cls.name} Class\n")
  output.add("###################\n\n")
  
  # Generate Nim object type with slots as fields
  # TODO: Eventually when we generate native methods directly, we can remove
  # classRef and toValue() - methods will be called directly instead of via sendMessage
  output.add("type\n")
  output.add(fmt("  {clsName}Obj* {{.inheritable.}} = object of {parentName}\n"))
  output.add(fmt("    classRef*: Class  ## Store class reference for toValue() (temporary - see above)\n"))
  
  # Slot fields - use NodeValue for flexibility in Harding
  for slot in slots:
    if not slot.isInherited:
      let slotName = mangleSlot(slot.name)
      output.add(fmt("    {slotName}*: NodeValue\n"))
  
  output.add(fmt("  {clsName}* = ref {clsName}Obj\n\n"))
  
  # Constructor
  output.add(fmt("proc new{clsName}*(): {clsName} =\n"))
  output.add(fmt("  ## Create new {cls.name} instance\n"))
  output.add(fmt("  result = {clsName}(new({clsName}Obj))\n"))
  # Get class reference from interpreter globals (temporary workaround)
  # This registers the class so toValue() can create proper Instance wrapper
  output.add(fmt("  if hybridInterpreter != nil:\n"))
  output.add(fmt("    if \"{cls.name}\" in hybridInterpreter.globals[]:\n"))
  output.add(fmt("      let clsVal = hybridInterpreter.globals[][\"{cls.name}\"]\n"))
  output.add(fmt("      if clsVal.kind == vkClass:\n"))
  output.add(fmt("        result.classRef = clsVal.classVal\n"))
  output.add(fmt("      elif clsVal.kind == vkInstance and clsVal.instVal != nil:\n"))
  output.add(fmt("        result.classRef = clsVal.instVal.class\n"))
  output.add(fmt("    elif \"Object\" in hybridInterpreter.globals[]:\n"))
  output.add(fmt("      let objVal = hybridInterpreter.globals[][\"Object\"]\n"))
  output.add(fmt("      if objVal.kind == vkInstance and objVal.instVal != nil:\n"))
  output.add(fmt("        result.classRef = objVal.instVal.class\n"))
  for slot in slots:
    if not slot.isInherited:
      output.add(fmt("  result.{mangleSlot(slot.name)} = NodeValue(kind: vkNil)\n"))
  output.add("\n")

  # toValue - convert native type to NodeValue using stored classRef
  # TODO: Remove when native method generation is complete
  output.add(fmt("proc toValue*(self: {clsName}): NodeValue =\n"))
  output.add(fmt("  ## Convert {cls.name} to NodeValue for sendMessage interop\n"))
  output.add(fmt("  let inst = Instance(kind: ikObject, class: self.classRef, isNimProxy: true, nimValue: cast[pointer](self))\n"))
  output.add(fmt("  return NodeValue(kind: vkInstance, instVal: inst)\n"))
  output.add("\n")
  
  return output

proc genClassInit*(cls: ClassInfo): string =
  ## Generate class initialization procedure (legacy - kept for compatibility)
  let clsName = mangleClass(cls.name)
  
  return fmt("""
# Legacy class init - use new{clsName}() constructor instead
# proc init_{clsName}*(): {clsName} = new{clsName}()

""")

proc genSlotAccessors*(cls: ClassInfo): string =
  ## Generate native Nim slot accessor procs for a class
  let clsName = mangleClass(cls.name)
  let slots = cls.getAllSlots()
  
  var output = ""
  if slots.len == 0:
    return output
  
  output.add("# Slot accessors\n")
  output.add("################################\n\n")
  
  for slot in slots:
    if slot.isInherited:
      continue
    let slotName = mangleSlot(slot.name)
    let capitalizedSlot = slot.name[0].toUpperAscii() & slot.name[1..^1]
    
    # Getter
    output.add(fmt("proc get{slotName}*(self: {clsName}): NodeValue =\n"))
    output.add(fmt("  ## Get slot '{slot.name}' from {cls.name}\n"))
    output.add(fmt("  return self[].{slotName}\n\n"))
    
    # Setter  
    output.add(fmt("proc set{slotName}*(self: {clsName}, value: NodeValue): NodeValue =\n"))
    output.add(fmt("  ## Set slot '{slot.name}' on {cls.name}\n"))
    output.add(fmt("  self[].{slotName} = value\n"))
    output.add(fmt("  return value\n\n"))
  
  return output

proc isClassDefinition(node: Node): bool =
  ## Check if a node is a class definition (derive: chain)
  if node.kind != nkMessage:
    return false
  let msg = node.MessageNode
  # Check for Class := Parent derive: ... pattern
  if msg.selector == "at:put:":
    if msg.arguments.len >= 2 and msg.arguments[1].kind == nkMessage:
      let valMsg = msg.arguments[1].MessageNode
      if valMsg.selector == "derive:" or valMsg.selector == "derive":
        return true
  return false

proc isMethodDefinition(node: Node): bool =
  ## Check if a node is a method definition (selector:put: or classSelector:put:)
  if node.kind != nkMessage:
    return false
  let msg = node.MessageNode
  return msg.selector in ["selector:put:", "classSelector:put:"]

proc extractClassAndMethodDefs(nodes: seq[Node]): tuple[defs: seq[Node], topLevel: seq[Node]] =
  ## Separate class/method definitions from top-level executable statements
  var defs: seq[Node] = @[]
  var topLevel: seq[Node] = @[]

  for node in nodes:
    if node.isClassDefinition or node.isMethodDefinition:
      defs.add(node)
    else:
      topLevel.add(node)

  return (defs, topLevel)

proc extractMethodDefs(nodes: seq[Node]): seq[tuple[className, selector: string, body: seq[Node]]] =
  ## Extract method definitions from AST nodes
  ## Returns (className, selector, body) for each method
  result = @[]
  
  for node in nodes:
    if node.kind == nkMessage:
      let msg = node.MessageNode
      if msg.selector == "selector:put:" and msg.arguments.len >= 2:
        var bodyBlock: BlockNode = nil
        if msg.arguments[1].kind == nkBlock:
          bodyBlock = msg.arguments[1].BlockNode
        elif msg.arguments[1].kind == nkLiteral:
          let litVal = msg.arguments[1].LiteralNode.value
          if litVal.kind == vkBlock:
            bodyBlock = litVal.blockVal
        
        if msg.arguments[0].kind == nkLiteral and bodyBlock != nil:
          let litVal = msg.arguments[0].LiteralNode.value
          let selectorName = if litVal.kind == vkSymbol: litVal.symVal 
                             elif litVal.kind == vkString: litVal.strVal
                             else: ""
          
          var className = ""
          if msg.receiver != nil and msg.receiver.kind == nkIdent:
            className = msg.receiver.IdentNode.name
          
          if className.len > 0 and selectorName.len > 0:
            result.add((className, selectorName, bodyBlock.body))

proc genCompiledMethods*(methodDefs: seq[tuple[className, selector: string, body: seq[Node]]],
                         compiledClasses: seq[string], classInfo: Table[string, ClassInfo]): string =
  ## Generate compiled method procs from extracted method definitions
  var output = ""
  
  if methodDefs.len == 0:
    return output
  
  output.add("\n# Compiled Methods\n")
  output.add("##################\n\n")
  
  for md in methodDefs:
    let clsName = md.className
    let selector = md.selector
    let body = md.body
    
    # Skip if class not in compiled classes
    if clsName notin compiledClasses:
      continue
    
    let mangledClass = mangleClass(clsName)
    let mangledSelector = mangleSelector(selector)
    let procName = fmt("{mangledClass}_{mangledSelector}")
    
    output.add(fmt("proc {procName}*(self: NodeValue): NodeValue =\n"))
    
    if body.len > 0:
      # Generate code for each statement in method body
      var genCtx = newGenContext(nil, compiledClasses, classInfo)
      genCtx.inMethod = true
      
      # Add 'self' as receiver
      genCtx.globals.add("self")
      
      let bodyLen = body.len
      for i, stmt in body:
        let isLast = (i == bodyLen - 1)
        let stmtCode = genMethodBodyStatement(genCtx, stmt, isLast)
        if stmtCode.len > 0:
          for line in stmtCode.splitLines():
            output.add("  ")
            output.add(line)
            output.add("\n")
    
    output.add("\n\n")
  
  return output

proc isHardingCompileBlock(node: Node): bool =
  ## Check if node is "Harding compile: [block]"
  if node.kind != nkMessage:
    return false
  let msg = node.MessageNode
  if msg.selector != "compile:":
    return false
  if msg.receiver == nil or msg.receiver.kind != nkIdent:
    return false
  return msg.receiver.IdentNode.name == "Harding"

proc isHardingMainBlock(node: Node): bool =
  ## Check if node is "Harding main: [block]"
  if node.kind != nkMessage:
    return false
  let msg = node.MessageNode
  if msg.selector != "main:":
    return false
  if msg.receiver == nil or msg.receiver.kind != nkIdent:
    return false
  return msg.receiver.IdentNode.name == "Harding"

proc extractHardingBlocks(nodes: seq[Node]): tuple[compileBlock, mainBlock: BlockNode, other: seq[Node]] =
  ## Extract Harding compile: and main: blocks from nodes
  result = (nil, nil, @[])
  
  for node in nodes:
    if node.isHardingCompileBlock:
      if node.MessageNode.arguments.len > 0 and node.MessageNode.arguments[0].kind == nkBlock:
        result.compileBlock = node.MessageNode.arguments[0].BlockNode
    elif node.isHardingMainBlock:
      if node.MessageNode.arguments.len > 0 and node.MessageNode.arguments[0].kind == nkBlock:
        result.mainBlock = node.MessageNode.arguments[0].BlockNode
    else:
      result.other.add(node)

proc genMainProc*(ctx: var CompilerContext, topLevel: seq[Node], moduleName: string,
                  blockReg: BlockRegistry = nil, compiledClasses: seq[string] = @[],
                  classInfo: Table[string, ClassInfo] = initTable[string, ClassInfo](),
                  mixed: bool = false, sourceFile: string = ""): string =
  ## Generate the main() procedure for top-level statement execution
  var output = ""

  output.add("# Main Entry Point\n")
  output.add("##################\n\n")

  output.add("proc main(): int =\n")
  output.add("  ## Main entry point for ")
  output.add(moduleName)
  output.add("\n")

  # Initialize runtime
  output.add("  initRuntime()\n\n")

  # If mixed mode, initialize hybrid runtime with source file
  if mixed and sourceFile.len > 0:
    output.add(fmt("  initHybridRuntime(@[\"{sourceFile}\"])\n\n"))

  # Create generation context for top-level code, sharing block registry if provided
  var genCtx = newGenContext(nil, compiledClasses, classInfo, mixed)
  if blockReg != nil:
    genCtx.blockRegistry = blockReg

  # Generate code for each top-level statement
  for node in topLevel:
    let stmtCode = genTopLevelStatement(genCtx, node)
    if stmtCode.len > 0:
      # Indent the statement
      for line in stmtCode.splitLines():
        output.add("  ")
        output.add(line)
        output.add("\n")

  # Return exit code 0
  output.add("\n  return 0\n")

  return output

proc genModule*(ctx: var CompilerContext, nodes: seq[Node],
                moduleName: string, mixed: bool = false, sourceFile: string = "",
                reflectedClasses: Table[string, ClassInfo] = initTable[string, ClassInfo]()): string =
  ## Generate complete Nim module from parsed nodes
  ## mixed: if true, embed interpreter for fallback on unsupported features
  ## sourceFile: path to source .hrd file for class registration in interpreter
  ## reflectedClasses: optional class info from interpreter execution (for dynamic classes)
  var output = ""

  output.add(genModuleHeader(ctx, moduleName))
  output.add(genRuntimeHelperMethods())
  output.add("\n")
  output.add(genBlockRuntimeHelpers())
  output.add("\n")

  # Separate class/method definitions from top-level statements
  let (classDefs, topLevel) = extractClassAndMethodDefs(nodes)

  # Extract Harding compile: and main: blocks
  let hardingBlocks = nodes.extractHardingBlocks()
  
  # Determine what to compile as main:
  # If there's a Harding main: block, use its body; otherwise use topLevel
  let mainBodyNodes = if hardingBlocks.mainBlock != nil:
                         hardingBlocks.mainBlock.body
                       else:
                         topLevel

  # Analyze classes - use reflected classes if provided, otherwise build from AST
  let analysis = if reflectedClasses.len > 0:
                   let result = newAnalysisResult()
                   result.classes = reflectedClasses
                   result
                 else:
                   buildClassGraph(nodes)

  # Resolve slot indices
  ctx.resolveSlotIndices()
  
  # Collect compiled class names for native instantiation
  var compiledClassNames: seq[string] = @[]
  for cls in analysis.classes.values:
    compiledClassNames.add(cls.name)

  # Generate base HardingObject type first
  output.add("# Base Object Type\n")
  output.add("##################\n\n")
  output.add("type\n")
  output.add("  HardingObject* {.inheritable.} = object\n")
  output.add("    className*: string\n")
  output.add("  HardingObjectRef* = ref HardingObject\n\n")

  # Generate for each class
  for cls in analysis.classes.values:
    output.add(genClassConstants(cls))
    output.add(genSlotAccessors(cls))
    output.add(genClassInit(cls))

  # Generate compiled methods from user definitions
  let methodDefs = extractMethodDefs(classDefs)
  output.add(genCompiledMethods(methodDefs, compiledClassNames, analysis.classes))

  # Generate control flow methods (must come before block procedures that may use them)
  output.add("\n")
  output.add("# Control Flow Methods\n")
  output.add("######################\n\n")

  output.add(genWhileTrueMethod())
  output.add(genWhileFalseMethod())
  output.add(genIfTrueIfFalseMethod())
  output.add(genTimesRepeatMethod())

  # Generate binary operators (must come before block procedures that may use them)
  output.add("\n")
  output.add("# Binary Operators\n")
  output.add("#################\n\n")

  for op in ["+", "-", "*", "/"]:
    output.add(genBinaryOpMethod(op))

  # Generate comparison operators
  output.add("\n")
  output.add("# Comparison Operators\n")
  output.add("#####################\n\n")

  for op in ["<", "<=", ">", ">=", "=", "==", "~="]:
    output.add(genComparisonMethod(op))

  # Generate integer division and modulo operators
  output.add("\n")
  output.add("# Integer Division and Modulo\n")
  output.add("#############################\n\n")

  output.add(genBinaryOpMethod("//"))
  output.add(genBinaryOpMethod("\\"))
  output.add(genBinaryOpMethod("%"))

  # Create a block registry and collect blocks
  # Note: top-level variables are NOT passed as knownGlobals because they are
  # locals of main() and need to be captured by block procs at module level.
  # Only true globals (class names) would be excluded from captures.
  var blockReg = newBlockRegistry()
  for node in mainBodyNodes:
    collectBlocks(blockReg, node)

  # Generate block procedure definitions (after primitives so they can reference them)
  output.add("\n")
  output.add("# Block Procedures\n")
  output.add("##################\n\n")

  # Generate environment structs for blocks with captures
  for blockInfo in blockReg.getAllBlocks():
    let structDef = generateEnvStructDef(blockInfo)
    if structDef.len > 0:
      output.add(structDef)
      output.add("\n\n")

  # Generate block procedure signatures and bodies using real code generation
  var blockGenCtx = newGenContext(nil, compiledClassNames, analysis.classes, mixed)
  for blockInfo in blockReg.getAllBlocks():
    output.add(generateBlockProcSignature(blockInfo))
    output.add(" =\n")
    let body = genBlockBody(blockGenCtx, blockInfo.blockNode, blockInfo.captures,
                            blockInfo.hasNonLocalReturn)
    if body.len > 0:
      output.add(body)
    else:
      output.add("  return NodeValue(kind: vkNil)\n")
    output.add("\n\n")

  # Generate main proc for top-level statements, sharing block registry
  output.add(genMainProc(ctx, mainBodyNodes, moduleName, blockReg, compiledClassNames, analysis.classes, mixed, sourceFile))

  # Module initialization
  output.add("\n")
  output.add("# Module Initialization\n")
  output.add("######################\n")

  output.add(fmt("""
proc init_{moduleName}*() =
  ## Initialize {moduleName} module
  initRuntime()
  echo "Module loaded: {moduleName}"

when isMainModule:
  discard main()
"""))

  return output

proc compileFile*(inputPath: string, outputDir = "./build"): string =
  ## Compile a Harding source file to Nim
  let source = readFile(inputPath)
  let tokens = lex(source)
  var parser = initParser(tokens)
  let nodes = parser.parseStatements()

  if parser.hasError:
    echo "Parse error: " & parser.errorMsg
    return ""

  let moduleName = inputPath.extractFilename().changeFileExt("")

  var ctx = newCompiler(outputDir, moduleName)
  let nimCode = genModule(ctx, nodes, moduleName)

  let outputPath = outputDir / moduleName & ".nim"
  createDir(outputDir)
  writeFile(outputPath, nimCode)

  return outputPath
